### PR TITLE
Debian packaging

### PR DESCRIPTION
**Pull request by Centuriondan**
Here is my debian packaging attempt.

It's my first ever attempt making a debian package so probably messy and missing bits etc.

### CODE REVIEW

**Comment by Xylemon** [comment]
It seems to be having some problems compiling for my friend here, what exact dependencies are needed on Debian?

**Comment by Centuriondan** [comment]
He should install and use git-buildpackage.

**Comment by Xylemon** [comment]
Alright sorry for the long responses, been busy with many things. So my friend was able to create a package but apparently it required tons of packages with these messages: http://puu.sh/erj6l/3c092aa5e1.png

Is there something we did wrong where it requires all these dependencies it deems unnecessary?

**Comment by Centuriondan** [comment]
Yeah,

Unfortunately, they are all dependencies pulled in by libgtk-3-0, and 
given that the toolkit has been updated to gtk3, it's required.  We 
could drop the gtk toolkit and go back to one to gtk2 or athena toolkit 
instead and that might reduce the dependencies.

D

On 13/01/15 13:22, Gethyn ThomasQuail wrote:
> Alright sorry for the long responses, been busy with many things. So my
> friend was able to create a package but apparently it required tons of
> packages with these messages: http://puu.sh/erj6l/3c092aa5e1.png
>
> Is there something we did wrong where it requires all these dependencies
> it deems unnecessary?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Xylemon/xlennart/pull/13#issuecomment-69673890>.
>


-- 
Daniel Reurich
Centurion Computer Technology (2005) Ltd.
021 797 722

**Comment by Xylemon** [comment]
It's your call, overall everything seems fine (despite the dependencies issue). If you want to commit anything else let me know, I'll then merge.

**Comment by Centuriondan** [comment]
I'll make the package release agnostic and rebase it to and then get you can merge after that.  We should file a rfp with debian and I'll ask devuan to include it as well.

On 13 January 2015 4:38:59 PM NZDT, Gethyn ThomasQuail <notifications@github.com> wrote:
>It's your call, overall everything seems fine (despite the dependencies
>issue). If you want to commit anything else let me know, I'll then
>merge.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Xylemon/xlennart/pull/13#issuecomment-69691043

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Xylemon** [comment]
Sounds good, keep me updated.

**Comment by Centuriondan** [comment]
This is ready to be pulled.

**Comment by Centuriondan** [comment]
oops :-)

**Comment by Xylemon** [comment]
Great! Also I was wondering if we could unify the Desktop files? I have a completely different comment and genre for the main one versus the one that comes with the Debian package. And I don't know any Italian, so my translation would probably be laughable.

**Pull request merged**
